jobs:
  build:

  deploy:
    name: Deploy
    needs: build
    ruons-on: ubuntu-latest
    if: github.ref == 'refs/head/main'

    steps:
      - name: Download artifact
        uses:: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist